version: '3.8'

services:

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    volumes:
        - ./server:/app
        - node_modules:/app/node_modules
    command: npm run start
    ports:
        - "3001:3000"
    depends_on:
      - db

  client-ui:
    container_name: client-ui
    working_dir: /client
    build:
      context: ./client-ui
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules
    command: sh -c "npm start"
    ports:
      - "3000:4200"


  db:
    container_name: database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=converter
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  node_modules:
  db:
    driver: local