export const CURRENCY_TYPE = [
  { code: 'USD', label: 'United States Dollar' },
  { code: 'ARS', label: 'Argentine Peso' },
  { code: 'AUD', label: 'Australian Dollar' },
  { code: 'BCH', label: 'Bitcoin Cash' },
  { code: 'BGN', label: 'Bulgarian Lev' },
  { code: 'BNB', label: 'Binance Coin' },
  { code: 'BRL', label: 'Brazilian Real' },
  { code: 'BTC', label: 'Bitcoin' },
  { code: 'CAD', label: 'Canadian Dollar' },
  { code: 'CHF', label: 'Swiss Franc' },
  { code: 'CNY', label: 'Chinese Yuan' },
  { code: 'CZK', label: 'Czech Republic Koruna' },
  { code: 'DKK', label: 'Danish Krone' },
  { code: 'DOGE', label: 'Dogecoin' },
  { code: 'DZD', label: 'Algerian Dinar' },
  { code: 'ETH', label: 'Ethereum' },
  { code: 'EUR', label: 'Euro' },
  { code: 'GBP', label: 'British Pound Sterling' },
  { code: 'HKD', label: 'Hong Kong Dollar' },
  { code: 'HRK', label: 'Croatian Kuna' },
  { code: 'HUF', label: 'Hungarian Forint' },
  { code: 'IDR', label: 'Indonesian Rupiah' },
  { code: 'ILS', label: 'Israeli New Sheqel' },
  { code: 'INR', label: 'Indian Rupee' },
  { code: 'ISK', label: 'Icelandic Króna' },
  { code: 'JPY', label: 'Japanese Yen' },
  { code: 'KRW', label: 'South Korean Won' },
  { code: 'LTC', label: 'Litecoin' },
  { code: 'MAD', label: 'Moroccan Dirham' },
  { code: 'MXN', label: 'Mexican Peso' },
  { code: 'MYR', label: 'Malaysian Ringgit' },
  { code: 'NOK', label: 'Norwegian Krone' },
  { code: 'NZD', label: 'New Zealand Dollar' },
  { code: 'PHP', label: 'Philippine Peso' },
  { code: 'PLN', label: 'Polish Zloty' },
  { code: 'RON', label: 'Romanian Leu' },
  { code: 'RUB', label: 'Russian Ruble' },
  { code: 'SEK', label: 'Swedish Krona' },
  { code: 'SGD', label: 'Singapore Dollar' },
  { code: 'THB', label: 'Thai Baht' },
  { code: 'TRY', label: 'Turkish Lira' },
  { code: 'TWD', label: 'New Taiwan Dollar' },
  { code: 'XRP', label: 'Ripple' },
  { code: 'ZAR', label: 'South African Rand' },
];
